# Default values for mmli-oed-api
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# Arbitrary configuration, unique to this application
config:
  # Defined as an encrypted SealedSecret (see below)
  # NOTE: This overrides the hardcoded values below
  existingSecret: moldb-oed-api

  # Alternatively, you can hardcode the values here instead (for local development only)
  # These are ignored if existingSecret is defined above
  OED_DB_USER: 'molfront'
  OED_DB_PASSWORD: ''   # See SealedSecret below
  OED_DB_HOST: 'moldb-postgres-r.moldb.svc.cluster.local'
  OED_DB_PORT: '5432'
  OED_DB_NAME: 'molfront'


# The Deployment captures everything about the container that will run
controller:
  # Define how many replicas of this application should run
  replicas: 1

  # Define which Docker image should be run for this application (container)
  image:
    repository: moleculemaker/mmli-oed-api
    pullPolicy: Always
    #pullSecrets: []

  # TODO: parameterize labels, tolerations, nodeSelector, resources, etc?


# Define how to access this application over the network
# The Service creates a static IP that will round-robin requests to the different replicas
service:
  type: ClusterIP
  protocol: TCP
  port: 8000


# Define whether / how to access this application over the public internet
ingress:
  enabled: true
  hostname: "openenzymedb-api.platform.moleculemaker.org"
  tls: true
  className: traefik
  annotations:
    # Automatically issue a TLS certificate for this ingress hostname
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production

    # Define Traefik strict TLS rules and Middlewares for ForwardAuth
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: openenzymedb-oed-staging-cors-header@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "true"


# TODO: in the future if this is split into prod/staging, this secret would likely be for staging
# Additional Kubernetes resources to deploy along with this Helm chart
# SealedSecrets, Middlewares, Volume definitions, etc
extraDeploy:
  # First, we build up in plaintext the Secret that we would like to encrypt (seal)
  # After building up a raw Secret, the cluster admin can encrypt them using the following command:
  #     kubeseal --format yaml < mmli-oed-api.moldb.secret.yaml > mmli-oed-api.moldb.sealedsecret.yaml
  # SealedSecrets can only be decrypted (unsealed) by our cluster's private key
  # This Secret will be automatically decrypted by our cluster, making it available to our application
  - apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      creationTimestamp: null
      name: moldb-oed-api
      namespace: openenzymedb
    spec:
      encryptedData:
        DATABASE_URL: AgACFLSQfUN1fz32sXDsQe2lE9C3uunxxvzX6SIcdLhVrkHLr0HFAFjE4WkoQWSXuAYn4fY3YU2uEgvRYFtYzW82vz+ul6ZV1zE2wDZA5Xnqtmc5WAuj/7EI8Vbx2UTKTRbBfpodQ7uXPyq3UorCJNul1OUQ5lEWz10rir+AKIHMis7TKMo/eQ1YsrnyfmsyzK+E0EMf9Vi7TaUsDig8gb/wrlCjprPsm08ktXzb9EKHbCSbcWmhY8OfmjVqwKWp/42R/gHMOUdEi7B+vwpJ+LX4CFhmSvfgWwGi6HigsRoW330AAnjxOf3L+KpUAQgt9tcMPZcjwO3EXBn5LENfZpWfilNzof+K7F4TGIjpk3J7J7Y0rDrcrYdyQ3p20lQweBcnnhna5VmgLb1+0pyf1gtSomMJHOUkE6S2z3XEdF4GnpEfyTtxrVHuFliNAv6v5Wu6kGk/uUcHh49UwwsD/W/+AZArZZqmX4GVWOXS1jw5zd9LDjmtVoVzzWsltdGucBmhrGoGH1RKyLfuf18OCxZKGlBE/t2LM0mYhQ+4jaqL4VRlH2zDQCtVfC3O+xJBLc857K0lVUUgqrOkwFLjvueUrsgukQFLJsEVTpXkcnaX8VBZVThyZJF7GUbvfZ42vfqT2NAyTAnpI2LD0lAwCl3GiPuGYRrO/ARQ4tWY7I/8ZfbiLdrQnxSui5V/DZaZ/hLQJDwIEHtvGvffrmzXtOmjyceVvDQOf5WgWEqCzpdPP5Aj71Mwy3rb5HylNdvEHueBm6SUnBsrfoKHlI78WnotasHigcBb/beCwiHvKd6HfBmyaelgxXMND6ts/yJfB+PYYZJl9MWFiYZTjA==
        OED_DB_HOST: AgAsA1KsV0174h8vqBTmCCDvRlo+URTjp3Mi58eD3jkQ8fqhPeflRHejs6/MsPuficL0XFbYSCq1i/Tb0qM5AxcKNTrHPNJ52PbvnkJoBRvYKw1brAqdoKG7XO+X8uNOvbBBzf/EJk2vpMIL89O33XpZBcY9r5qZNo0k8waK029ispWN5NH92zZFxWQ+zVPwnaP7mo/l+tDNE5kO2vlOZm15glf4MFQ8U6e4UmvX01VtVzPMd3dAvWw1nQ/rBpj9xrwFKhW7g13IYZ4AEJY3GTwdpCTAyEnisxX3of1pe5dZGeAEeSh/uTzOFvHUgWbsn3VXwlDlNHLzJkR2WJOeyNJLc4CYcZCbKr/gsXY5E0ny8vRQQYx3K5HfkM50fQlspfk9rQn0v2BFM9E7n4P9+R2iFpimcyFpGF2cuOVYCFrSN5rhMNdfpwaAL3MOdFNWf+LXxgDitCWl9Tz3RcqcB2vwAfMg+16dDnRP5h3CGcpYPaUBNe7sO3N2Zze5t/hjrJ6LlOvdHC0jLmmw6ZzoNNf0/6Xxe7S/Aj7gKFieiMZ13lLZpTyxRSIh9QPmCu+a6Jd8ezaaH+w65HdtQZPGhQOPjZgMbhsoVhuMkh7B4wVwiZ6cnPButF5f6daEFJRCr5HYSK5zUhe1VeNtBkT1xWf0e8umFWJZoHW2/kQ7EWsm/VE159NLwPd8en/5OOVdqpofOGQ5u0O36dJYfEFusladpZRZ+m2yzJz4shM08Aehuu+NxmvrdzU4
        OED_DB_NAME: AgDRRW2knrdGJbKBVTgAGncKxWxLCNjnURerNQkrqgWfUUYDMZ1WgqYzhtszkgchWutFZ1h3mE1j74407W4T6kyBXAabKrYEkrNqmreOFMd1vu7LdCMaZCKDqrjxOaOgklYJdtvpxnevJJqBykODuiLVwobaQrCUSfkHJUjktvfS2t3jAeEE0V6hFPHy/6GoeWPegB1Re0OpTEuocY7psvVMLIX/bw6RWl5JlDgsL5VckQs4hc7SGdIHtfxuQ2TbymkjPC5ule+S69FqvUWezctJxghWDUXwbQo9ursds70JTKD+fnz6rJGtB4J+0F568NS0maLJ8QPRrwJLRuwRPFidepIL6q5st7gOK48Pj5Cl1iq7b7Bi/MAzLUWsQTPMy3PMKOm6y7sJcU7QsjnfhJppYQNw/BLP3ZbcCUE2Kw3D2Gwyj7o6qKMlxEQXLqq7F9nqbPMhrRvunX961qJr3avlkrGysIJQztRIVgI3AoQLMDMFp1Lwv5rsQEj5PT2iEWcsM7bTIhkdmq+skkdU3PWTU8z8wrTAtGvzvf/cKMuLTIX6MxNJC/g1va9cLLRl+VZlgIMBl4haQ9EmKH20VSh2mdaHnsg6Fm6blzdNlZBghqUwg505U+QfI9os5bfilSuYOlXSVvamWsrVXf+V0rlK21X7hOhb8x8c2aN1K0tU7mnH21Ccpl4qjsT1feDcPHES/vZ6lldhVg==
        OED_DB_PASSWORD: AgAmznrraIDUk3p5k6J3rBglDmE/T2IleMmHuMfqqRLQP3X+g9gi98jRTa8EJGHz3eiW0dVGMRD9tz38Xn9LH/s95d20ojLB5rp2yJVk8+e+l+e7EwA/wlHljRg1YBFCFST2zYKv9BDfmjl2g8QirXUAjmcQtq2de+X+OlOwoT/oGmRgbEfgbYc21HQcqtcHmlzmXC/EihTMhJxBgEFcOp15uk+yc0sVR6rm5NJ5eUSMb/0qmE249Q8Ct4Y17Q76VOGPtYV3VCCVD825uVb5YNe03TZ4xL+KsPnAozV5Tywi4USIVyLpYi4+HJ7KqpKFAEjhAl2cubLcRVWDBel9tPl2YubjYPkEAFKLxUC0BqfivyykevY8Efc8CyYAuNex8CrfAfnZAnaDSnXHZsXtM4gl4jsyc03jOjSNsWfYn0mN40Mojgsq7ZScL0FladDC3h0jRVwVebcdfFOKrWeCmwdPI3CaQYr3fFiGSNUB+2Ttwsk2lrWaGJE8dMLrGsBmvfO90AF2Wskc1cK7cEoniGwMUFakJxUgio1R9B902mE5H6B0ajTO9OiJZnOGOjpQ8bvMZ7kJ/2yRbs2Q/7Z1mUDfC4gICo1S25zdn5ADfphUoQagEWncjR7hDZambWGYoYckIsmfB1dvGDYmAm4mHKjWfIkyah9o4Pa3XK5GADwtP8rcmWBTgLpmgCo6dBR7yXL6+xHy4z2nDT6Nbyj3iJYZvS4xH3vfJ85BZEMYKqPi9Q==
        OED_DB_PORT: AgDcogJqFXRNAdi7TiafM2LcRXg7n7NHyCB8DjqES3X8BruW3+b30lQfe5KEkdJeuCnPoe5I3qU6suUfXTsJ3jAckwxAIp08N+xJxR4Qj8NqvvngbMKRG/wqyVGiJClotZDAkqhmhjlnIaoe41x4fx+WhwQZpKLlKipQ/hPznzCkCFcVzhZDVcJMoBwqWp67mhAhhAEx/bo+q9wbZfHARXCPMgSwYBGuqZNjgIfEpDFH+N6wt/5xGOzO5YTF26F3N9+kwim+08UC86l5T6e+lD6FkVHoMIaCThiuEjoxQ/g9zvQBA7FxO2lWyUAqlF2a8pvx+1USml7Qem9QS8zuOhU3uKBe1yEtv5iDqxeI/i0dubLuDyBFF8Qjamoul3csDIrCYvC0Ri40hu9MlX0H8tlQ3+ulRviO6rEkTNlE+bDdlXau3I4WqjgCkSAB4DQX3okN1HilIegTy86o5QLn6X+hhQPLZpwJVIxWyBwK6TvYRrvPCWyD4XUpfmF4TvV7G4aAW0Gi63UhxE8P+nnOA4iOOd0/BTe5iTVufI3L+yW3+mbM8xU6OcnP5rNmOiyoyI6zRJ6i1aRBJkMDbj3ixFsJ0ApOD0B21FoInE1NwADl/KfegSpGje6hbn+W/Vi+V6fRWKBQLZUhJh43zSOG72Mv27MzxTEA13XCoWJdoUCrl/F5b0rrCjvl4tJCu9u92H945BCd
        OED_DB_USER: AgBDXFEMnCIDkWTErGsAhyiasEyLse/6mWl/xL+e5RQDYtYl+5Gs1Hz2XS1l7mhiuy6ibr8D+wIyrY5MCf5Xu2xRV0bmJRHHBD1rPjqYx4ZBoYitzklb9sox6aOot7gs8I2QbVPSZwy5eDahm8+8JxzmaeNcICR/tGaZGAYAlSk3Tr0RWfA1H5Q0YpVryc1xzr3qixYzTot6SvZngIdI1rbQ9vPxI5WXgDLpdqSMpM+mIeT/VW1sc9QCvjN5JOtGQgnyrtyWNjbZZKy90RgbsyieDaw+QCbbLE9pHSL0CZ56PhcXc6VmJ+57pm3AxulJf5QiZFRPHat4suXuTmPBQwesh1+M1Qh44q8xe/DxxcToQx8QYyC1eFrkBtQsHlUP5GaLeJnmcxOOfaBkPuoeLUnQtymMwcQh4jEwZ+y+OIE4YOMvO4VaijRmCLiNDfrM2QWY8W0NR8PV42szEomL2X3qnZfkpHDXk6sRIMYf8svkyYbIel5d7njIMqXNhpXvFJG62GcupV7CBMikThVd1Wr+mkJjCys9+aKyRASJMOOGKmq1VU0yCyGNYn5amqYazRA3y3hQa0OdMfzu2szhV8l0Rxo3JaheW5sUVuxdUVaAX+gnZq+KNSUX5AFMdvXE/IETYfzuLa15v374y/du953V7mdX3kk8+8VMiyr+Qcu4JCt4UYs2KLTH4z9lWt+L39V0ffIODZNIuQ==
      template:
        metadata:
          creationTimestamp: null
          name: moldb-oed-api
          namespace: openenzymedb
        type: Opaque
