{{- if .Values.ingress.enabled }}
# Enables the pods in a deployment to be accessible from outside the cluster
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
{{- with .Values.ingress.annotations }}
  annotations:
  {{ toYaml . | nindent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ .Values.ingress.hostname }}-tls
{{- end }}
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
  rules:
  - host: {{ .Values.ingress.hostname | required "required: ingress.hostname (e.g. oedapi.proxy.localhost)" }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ .Values.service.port }}
        path: /
        pathType: ImplementationSpecific
{{- end }}